// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audio.sql

package store

import (
	"context"
)

const abandonedTagJobs = `-- name: AbandonedTagJobs :many
SELECT t.id, t.user_id, t.file_id, t.fingerprint, t.patch, t.phase, t.error, t.updated_at FROM audio_tag_jobs t JOIN jobs j ON j.id=t.id
WHERE j.state IN ('failed','cancelled') AND t.phase NOT IN ('indexed','abandoned') LIMIT 100
`

func (q *Queries) AbandonedTagJobs(ctx context.Context) ([]AudioTagJob, error) {
	rows, err := q.db.Query(ctx, abandonedTagJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AudioTagJob{}
	for rows.Next() {
		var i AudioTagJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileID,
			&i.Fingerprint,
			&i.Patch,
			&i.Phase,
			&i.Error,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activeDownloads = `-- name: ActiveDownloads :one
SELECT count(*) FROM jobs WHERE role='downloader' AND state='running' AND lease_until>now()
`

func (q *Queries) ActiveDownloads(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, activeDownloads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const audioChildren = `-- name: AudioChildren :many
SELECT i.id, i.library_id, i.parent_id, i.kind, i.title, i.sort_title, i.year, i.season, i.episode, i.overview, i.poster, i.provider_id, i.metadata_locked, i.created_at, i.cast_members FROM items i LEFT JOIN audio_collection_members m ON m.item_id=i.id AND m.collection_id=$1
WHERE i.parent_id=$1 OR m.collection_id=$1 ORDER BY i.season,COALESCE(m.ordinal,i.episode),i.sort_title,i.id
`

func (q *Queries) AudioChildren(ctx context.Context, collectionID string) ([]Item, error) {
	rows, err := q.db.Query(ctx, audioChildren, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.ParentID,
			&i.Kind,
			&i.Title,
			&i.SortTitle,
			&i.Year,
			&i.Season,
			&i.Episode,
			&i.Overview,
			&i.Poster,
			&i.ProviderID,
			&i.MetadataLocked,
			&i.CreatedAt,
			&i.CastMembers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const canImport = `-- name: CanImport :one
SELECT EXISTS(SELECT 1 FROM users u JOIN libraries l ON l.id=$1
WHERE u.id=$2 AND NOT u.disabled AND l.kind IN ('music','podcasts','audiobooks')
AND (u.role='admin' OR EXISTS(SELECT 1 FROM library_access a WHERE a.user_id=u.id AND a.library_id=l.id AND a.can_import)))::boolean
`

type CanImportParams struct {
	LibraryID string
	UserID    string
}

func (q *Queries) CanImport(ctx context.Context, arg CanImportParams) (bool, error) {
	row := q.db.QueryRow(ctx, canImport, arg.LibraryID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const cancelSourceJobs = `-- name: CancelSourceJobs :exec
UPDATE jobs SET cancel_requested=true,state=CASE WHEN state='pending' THEN 'cancelled' ELSE state END
WHERE resource_id=$1 AND role='downloader' AND state IN ('pending','running')
`

func (q *Queries) CancelSourceJobs(ctx context.Context, resourceID string) error {
	_, err := q.db.Exec(ctx, cancelSourceJobs, resourceID)
	return err
}

const createImportSource = `-- name: CreateImportSource :one
INSERT INTO import_sources(id,user_id,library_id,url,title,follow) VALUES($1,$2,$3,$4,$5,$6) RETURNING id, user_id, library_id, url, title, follow, paused, next_sync_at, created_at
`

type CreateImportSourceParams struct {
	ID        string
	UserID    string
	LibraryID string
	Url       string
	Title     string
	Follow    bool
}

func (q *Queries) CreateImportSource(ctx context.Context, arg CreateImportSourceParams) (ImportSource, error) {
	row := q.db.QueryRow(ctx, createImportSource,
		arg.ID,
		arg.UserID,
		arg.LibraryID,
		arg.Url,
		arg.Title,
		arg.Follow,
	)
	var i ImportSource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LibraryID,
		&i.Url,
		&i.Title,
		&i.Follow,
		&i.Paused,
		&i.NextSyncAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteImportSource = `-- name: DeleteImportSource :exec
DELETE FROM import_sources WHERE id=$1
`

func (q *Queries) DeleteImportSource(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteImportSource, id)
	return err
}

const dueImportSources = `-- name: DueImportSources :many
SELECT id, user_id, library_id, url, title, follow, paused, next_sync_at, created_at FROM import_sources WHERE follow AND NOT paused AND next_sync_at<=now()
`

func (q *Queries) DueImportSources(ctx context.Context) ([]ImportSource, error) {
	rows, err := q.db.Query(ctx, dueImportSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportSource{}
	for rows.Next() {
		var i ImportSource
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LibraryID,
			&i.Url,
			&i.Title,
			&i.Follow,
			&i.Paused,
			&i.NextSyncAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAudioMetadata = `-- name: GetAudioMetadata :one
SELECT item_id, tags, chapters FROM audio_metadata WHERE item_id=$1
`

func (q *Queries) GetAudioMetadata(ctx context.Context, itemID string) (AudioMetadatum, error) {
	row := q.db.QueryRow(ctx, getAudioMetadata, itemID)
	var i AudioMetadatum
	err := row.Scan(&i.ItemID, &i.Tags, &i.Chapters)
	return i, err
}

const getImportSource = `-- name: GetImportSource :one
SELECT id, user_id, library_id, url, title, follow, paused, next_sync_at, created_at FROM import_sources WHERE id=$1
`

func (q *Queries) GetImportSource(ctx context.Context, id string) (ImportSource, error) {
	row := q.db.QueryRow(ctx, getImportSource, id)
	var i ImportSource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LibraryID,
		&i.Url,
		&i.Title,
		&i.Follow,
		&i.Paused,
		&i.NextSyncAt,
		&i.CreatedAt,
	)
	return i, err
}

const getImportedFile = `-- name: GetImportedFile :one
SELECT library_id, video_id, path FROM imported_files WHERE library_id=$1 AND video_id=$2
`

type GetImportedFileParams struct {
	LibraryID string
	VideoID   string
}

func (q *Queries) GetImportedFile(ctx context.Context, arg GetImportedFileParams) (ImportedFile, error) {
	row := q.db.QueryRow(ctx, getImportedFile, arg.LibraryID, arg.VideoID)
	var i ImportedFile
	err := row.Scan(&i.LibraryID, &i.VideoID, &i.Path)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, role, kind, resource_id, state, payload, error, progress, attempts, lease_id, lease_until, cancel_requested, created_at, updated_at, total_files, processed_files, next_attempt_at FROM jobs WHERE id=$1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Kind,
		&i.ResourceID,
		&i.State,
		&i.Payload,
		&i.Error,
		&i.Progress,
		&i.Attempts,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.CancelRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalFiles,
		&i.ProcessedFiles,
		&i.NextAttemptAt,
	)
	return i, err
}

const getTagJob = `-- name: GetTagJob :one
SELECT id, user_id, file_id, fingerprint, patch, phase, error, updated_at FROM audio_tag_jobs WHERE id=$1
`

func (q *Queries) GetTagJob(ctx context.Context, id string) (AudioTagJob, error) {
	row := q.db.QueryRow(ctx, getTagJob, id)
	var i AudioTagJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileID,
		&i.Fingerprint,
		&i.Patch,
		&i.Phase,
		&i.Error,
		&i.UpdatedAt,
	)
	return i, err
}

const grantImport = `-- name: GrantImport :exec
UPDATE library_access SET can_import=true WHERE user_id=$1 AND library_id=$2
`

type GrantImportParams struct {
	UserID    string
	LibraryID string
}

func (q *Queries) GrantImport(ctx context.Context, arg GrantImportParams) error {
	_, err := q.db.Exec(ctx, grantImport, arg.UserID, arg.LibraryID)
	return err
}

const libraryImportSources = `-- name: LibraryImportSources :many
SELECT id, user_id, library_id, url, title, follow, paused, next_sync_at, created_at FROM import_sources WHERE library_id=$1
`

func (q *Queries) LibraryImportSources(ctx context.Context, libraryID string) ([]ImportSource, error) {
	rows, err := q.db.Query(ctx, libraryImportSources, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportSource{}
	for rows.Next() {
		var i ImportSource
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LibraryID,
			&i.Url,
			&i.Title,
			&i.Follow,
			&i.Paused,
			&i.NextSyncAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudioArtists = `-- name: ListAudioArtists :many
SELECT DISTINCT artist.value::text AS name FROM audio_metadata a
JOIN items i ON i.id=a.item_id CROSS JOIN LATERAL jsonb_array_elements_text(a.tags->'artists') artist(value)
WHERE i.library_id=$1 AND artist.value<>'' ORDER BY name
`

func (q *Queries) ListAudioArtists(ctx context.Context, libraryID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAudioArtists, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudioJobs = `-- name: ListAudioJobs :many
SELECT j.id, j.role, j.kind, j.resource_id, j.state, j.payload, j.error, j.progress, j.attempts, j.lease_id, j.lease_until, j.cancel_requested, j.created_at, j.updated_at, j.total_files, j.processed_files, j.next_attempt_at FROM jobs j LEFT JOIN import_sources s ON s.id=j.resource_id
LEFT JOIN audio_tag_jobs t ON t.id=j.id LEFT JOIN media_files f ON f.id=t.file_id LEFT JOIN items i ON i.id=f.item_id
JOIN users u ON u.id=$1
WHERE j.kind IN ('youtube_preview','youtube_download','audio_tags')
AND (u.role='admin' OR ((s.user_id=u.id OR t.user_id=u.id) AND EXISTS(SELECT 1 FROM library_access a WHERE a.user_id=u.id AND a.library_id=COALESCE(s.library_id,i.library_id))))
ORDER BY j.created_at DESC LIMIT 100
`

func (q *Queries) ListAudioJobs(ctx context.Context, userID string) ([]Job, error) {
	rows, err := q.db.Query(ctx, listAudioJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Kind,
			&i.ResourceID,
			&i.State,
			&i.Payload,
			&i.Error,
			&i.Progress,
			&i.Attempts,
			&i.LeaseID,
			&i.LeaseUntil,
			&i.CancelRequested,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalFiles,
			&i.ProcessedFiles,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportEntries = `-- name: ListImportEntries :many
SELECT source_id, video_id, title, ordinal, state, error FROM import_entries WHERE source_id=$1 ORDER BY ordinal,video_id
`

func (q *Queries) ListImportEntries(ctx context.Context, sourceID string) ([]ImportEntry, error) {
	rows, err := q.db.Query(ctx, listImportEntries, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportEntry{}
	for rows.Next() {
		var i ImportEntry
		if err := rows.Scan(
			&i.SourceID,
			&i.VideoID,
			&i.Title,
			&i.Ordinal,
			&i.State,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportSources = `-- name: ListImportSources :many
SELECT s.id, s.user_id, s.library_id, s.url, s.title, s.follow, s.paused, s.next_sync_at, s.created_at FROM import_sources s JOIN users u ON u.id=$1
WHERE u.role='admin' OR (s.user_id=u.id AND EXISTS(SELECT 1 FROM library_access a WHERE a.user_id=u.id AND a.library_id=s.library_id)) ORDER BY s.created_at DESC
`

func (q *Queries) ListImportSources(ctx context.Context, userID string) ([]ImportSource, error) {
	rows, err := q.db.Query(ctx, listImportSources, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportSource{}
	for rows.Next() {
		var i ImportSource
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LibraryID,
			&i.Url,
			&i.Title,
			&i.Follow,
			&i.Paused,
			&i.NextSyncAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDownloads = `-- name: LockDownloads :exec
SELECT pg_advisory_xact_lock(7311903)
`

func (q *Queries) LockDownloads(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockDownloads)
	return err
}

const saveAudioMember = `-- name: SaveAudioMember :exec
INSERT INTO audio_collection_members(collection_id,item_id,ordinal) VALUES($1,$2,$3) ON CONFLICT(collection_id,item_id) DO NOTHING
`

type SaveAudioMemberParams struct {
	CollectionID string
	ItemID       string
	Ordinal      int32
}

func (q *Queries) SaveAudioMember(ctx context.Context, arg SaveAudioMemberParams) error {
	_, err := q.db.Exec(ctx, saveAudioMember, arg.CollectionID, arg.ItemID, arg.Ordinal)
	return err
}

const saveAudioMetadata = `-- name: SaveAudioMetadata :exec
INSERT INTO audio_metadata(item_id,tags,chapters) VALUES($1,$2,$3)
ON CONFLICT(item_id) DO UPDATE SET tags=excluded.tags,chapters=excluded.chapters
`

type SaveAudioMetadataParams struct {
	ItemID   string
	Tags     []byte
	Chapters []byte
}

func (q *Queries) SaveAudioMetadata(ctx context.Context, arg SaveAudioMetadataParams) error {
	_, err := q.db.Exec(ctx, saveAudioMetadata, arg.ItemID, arg.Tags, arg.Chapters)
	return err
}

const saveImportEntry = `-- name: SaveImportEntry :exec
INSERT INTO import_entries(source_id,video_id,title,ordinal) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING
`

type SaveImportEntryParams struct {
	SourceID string
	VideoID  string
	Title    string
	Ordinal  int32
}

func (q *Queries) SaveImportEntry(ctx context.Context, arg SaveImportEntryParams) error {
	_, err := q.db.Exec(ctx, saveImportEntry,
		arg.SourceID,
		arg.VideoID,
		arg.Title,
		arg.Ordinal,
	)
	return err
}

const saveImportedFile = `-- name: SaveImportedFile :exec
INSERT INTO imported_files(library_id,video_id,path) VALUES($1,$2,$3) ON CONFLICT DO NOTHING
`

type SaveImportedFileParams struct {
	LibraryID string
	VideoID   string
	Path      string
}

func (q *Queries) SaveImportedFile(ctx context.Context, arg SaveImportedFileParams) error {
	_, err := q.db.Exec(ctx, saveImportedFile, arg.LibraryID, arg.VideoID, arg.Path)
	return err
}

const saveTagJob = `-- name: SaveTagJob :exec
INSERT INTO audio_tag_jobs(id,user_id,file_id,fingerprint,patch) VALUES($1,$2,$3,$4,$5)
`

type SaveTagJobParams struct {
	ID          string
	UserID      string
	FileID      string
	Fingerprint string
	Patch       []byte
}

func (q *Queries) SaveTagJob(ctx context.Context, arg SaveTagJobParams) error {
	_, err := q.db.Exec(ctx, saveTagJob,
		arg.ID,
		arg.UserID,
		arg.FileID,
		arg.Fingerprint,
		arg.Patch,
	)
	return err
}

const scheduleImportSource = `-- name: ScheduleImportSource :exec
UPDATE import_sources SET next_sync_at=now()+interval '6 hours',title=CASE WHEN $2::text='' THEN title ELSE $2 END WHERE id=$1
`

type ScheduleImportSourceParams struct {
	ID      string
	Column2 string
}

func (q *Queries) ScheduleImportSource(ctx context.Context, arg ScheduleImportSourceParams) error {
	_, err := q.db.Exec(ctx, scheduleImportSource, arg.ID, arg.Column2)
	return err
}

const setImportEntry = `-- name: SetImportEntry :exec
UPDATE import_entries SET state=$3,error=$4 WHERE source_id=$1 AND video_id=$2
`

type SetImportEntryParams struct {
	SourceID string
	VideoID  string
	State    string
	Error    string
}

func (q *Queries) SetImportEntry(ctx context.Context, arg SetImportEntryParams) error {
	_, err := q.db.Exec(ctx, setImportEntry,
		arg.SourceID,
		arg.VideoID,
		arg.State,
		arg.Error,
	)
	return err
}

const setTagPhase = `-- name: SetTagPhase :exec
UPDATE audio_tag_jobs SET phase=$2,error=$3,updated_at=now() WHERE id=$1
`

type SetTagPhaseParams struct {
	ID    string
	Phase string
	Error string
}

func (q *Queries) SetTagPhase(ctx context.Context, arg SetTagPhaseParams) error {
	_, err := q.db.Exec(ctx, setTagPhase, arg.ID, arg.Phase, arg.Error)
	return err
}

const setWorkerCapabilities = `-- name: SetWorkerCapabilities :exec
UPDATE workers SET capabilities=$2 WHERE id=$1
`

type SetWorkerCapabilitiesParams struct {
	ID           string
	Capabilities []byte
}

func (q *Queries) SetWorkerCapabilities(ctx context.Context, arg SetWorkerCapabilitiesParams) error {
	_, err := q.db.Exec(ctx, setWorkerCapabilities, arg.ID, arg.Capabilities)
	return err
}

const updateAudioTitle = `-- name: UpdateAudioTitle :exec
UPDATE items SET title=$2,sort_title=lower($2),year=$3,poster=$4 WHERE id=$1 AND NOT metadata_locked
`

type UpdateAudioTitleParams struct {
	ID     string
	Title  string
	Year   int32
	Poster string
}

func (q *Queries) UpdateAudioTitle(ctx context.Context, arg UpdateAudioTitleParams) error {
	_, err := q.db.Exec(ctx, updateAudioTitle,
		arg.ID,
		arg.Title,
		arg.Year,
		arg.Poster,
	)
	return err
}

const updateImportSource = `-- name: UpdateImportSource :one
UPDATE import_sources SET paused=$2,follow=$3 WHERE id=$1 RETURNING id, user_id, library_id, url, title, follow, paused, next_sync_at, created_at
`

type UpdateImportSourceParams struct {
	ID     string
	Paused bool
	Follow bool
}

func (q *Queries) UpdateImportSource(ctx context.Context, arg UpdateImportSourceParams) (ImportSource, error) {
	row := q.db.QueryRow(ctx, updateImportSource, arg.ID, arg.Paused, arg.Follow)
	var i ImportSource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LibraryID,
		&i.Url,
		&i.Title,
		&i.Follow,
		&i.Paused,
		&i.NextSyncAt,
		&i.CreatedAt,
	)
	return i, err
}

const userImports = `-- name: UserImports :many
SELECT library_id FROM library_access WHERE user_id=$1 AND can_import
`

func (q *Queries) UserImports(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, userImports, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var library_id string
		if err := rows.Scan(&library_id); err != nil {
			return nil, err
		}
		items = append(items, library_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validJobLease = `-- name: ValidJobLease :one
SELECT EXISTS(SELECT 1 FROM jobs WHERE id=$1 AND lease_id=$2 AND state='running' AND NOT cancel_requested AND lease_until>now())::boolean
`

type ValidJobLeaseParams struct {
	ID      string
	LeaseID string
}

func (q *Queries) ValidJobLease(ctx context.Context, arg ValidJobLeaseParams) (bool, error) {
	row := q.db.QueryRow(ctx, validJobLease, arg.ID, arg.LeaseID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
