// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"
)

type AudioCollectionMember struct {
	CollectionID string
	ItemID       string
	Ordinal      int32
}

type AudioMetadatum struct {
	ItemID   string
	Tags     []byte
	Chapters []byte
}

type AudioTagJob struct {
	ID          string
	UserID      string
	FileID      string
	Fingerprint string
	Patch       []byte
	Phase       string
	Error       string
	UpdatedAt   time.Time
}

type ImportEntry struct {
	SourceID string
	VideoID  string
	Title    string
	Ordinal  int32
	State    string
	Error    string
}

type ImportSource struct {
	ID         string
	UserID     string
	LibraryID  string
	Url        string
	Title      string
	Follow     bool
	Paused     bool
	NextSyncAt time.Time
	CreatedAt  time.Time
}

type ImportedFile struct {
	LibraryID string
	VideoID   string
	Path      string
}

type Item struct {
	ID             string
	LibraryID      string
	ParentID       string
	Kind           string
	Title          string
	SortTitle      string
	Year           int32
	Season         int32
	Episode        int32
	Overview       string
	Poster         string
	ProviderID     string
	MetadataLocked bool
	CreatedAt      time.Time
	CastMembers    []byte
}

type Job struct {
	ID              string
	Role            string
	Kind            string
	ResourceID      string
	State           string
	Payload         []byte
	Error           string
	Progress        int32
	Attempts        int32
	LeaseID         string
	LeaseUntil      time.Time
	CancelRequested bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	TotalFiles      int32
	ProcessedFiles  int32
	NextAttemptAt   time.Time
}

type Library struct {
	ID                string
	Name              string
	Kind              string
	Paths             []string
	ScanIntervalHours int32
	LastScanAt        time.Time
}

type LibraryAccess struct {
	UserID    string
	LibraryID string
	CanImport bool
}

type MediaFile struct {
	ID         string
	ItemID     string
	Path       string
	Size       int64
	ModifiedAt int64
	Duration   float64
	Probe      []byte
	Available  bool
}

type PlaybackSession struct {
	ID            string
	UserID        string
	ItemID        string
	FileID        string
	TokenHash     string
	Method        string
	State         string
	StartPosition float64
	Sequence      int64
	Position      float64
	ExpiresAt     time.Time
	UpdatedAt     time.Time
	Decision      []byte
}

type Session struct {
	TokenHash string
	UserID    string
	ExpiresAt time.Time
}

type Setting struct {
	Key   string
	Value []byte
}

type UploadedSubtitle struct {
	ID        string
	FileID    string
	UserID    string
	Name      string
	Cues      []byte
	CreatedAt time.Time
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    time.Time
}

type UserState struct {
	UserID    string
	ItemID    string
	Favorite  bool
	Watched   bool
	Position  float64
	UpdatedAt time.Time
}

type Worker struct {
	ID           string
	Role         string
	HeartbeatAt  time.Time
	Capabilities []byte
}
