// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"time"
)

const activeTranscodes = `-- name: ActiveTranscodes :one
SELECT count(*) FROM jobs WHERE role='transcoder' AND state='running' AND lease_until>now()
`

func (q *Queries) ActiveTranscodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, activeTranscodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const authenticate = `-- name: Authenticate :one
SELECT u.id, u.username, u.password_hash, u.role, u.disabled, u.created_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now() AND NOT u.disabled
`

func (q *Queries) Authenticate(ctx context.Context, tokenHash string) (User, error) {
	row := q.db.QueryRow(ctx, authenticate, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const canAccess = `-- name: CanAccess :one
SELECT EXISTS(SELECT 1 FROM libraries l WHERE l.id=$1 AND ($3::boolean OR EXISTS(SELECT 1 FROM library_access a WHERE a.library_id=l.id AND a.user_id=$2)))::boolean
`

type CanAccessParams struct {
	ID      string
	UserID  string
	Column3 bool
}

func (q *Queries) CanAccess(ctx context.Context, arg CanAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, canAccess, arg.ID, arg.UserID, arg.Column3)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const cancelJob = `-- name: CancelJob :exec
UPDATE jobs SET cancel_requested=true,state=CASE WHEN state='pending' THEN 'cancelled' ELSE state END WHERE id=$1 AND state IN ('pending','running')
`

func (q *Queries) CancelJob(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, cancelJob, id)
	return err
}

const cancelPlaybackJobs = `-- name: CancelPlaybackJobs :exec
UPDATE jobs SET cancel_requested=true WHERE resource_id=$1 AND role='transcoder' AND state IN ('running','pending')
`

func (q *Queries) CancelPlaybackJobs(ctx context.Context, resourceID string) error {
	_, err := q.db.Exec(ctx, cancelPlaybackJobs, resourceID)
	return err
}

const claimJob = `-- name: ClaimJob :one
WITH candidate AS (SELECT j.id FROM jobs j WHERE j.role=$1 AND next_attempt_at<=now() AND NOT cancel_requested AND attempts<3 AND (state='pending' OR (state='running' AND lease_until<now() AND j.role IN ('scanner','downloader'))) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1)
UPDATE jobs SET state='running',progress=0,total_files=0,processed_files=0,attempts=attempts+1,lease_id=$2,lease_until=now()+interval '30 seconds',updated_at=now() FROM candidate WHERE jobs.id=candidate.id RETURNING jobs.id, jobs.role, jobs.kind, jobs.resource_id, jobs.state, jobs.payload, jobs.error, jobs.progress, jobs.attempts, jobs.lease_id, jobs.lease_until, jobs.cancel_requested, jobs.created_at, jobs.updated_at, jobs.total_files, jobs.processed_files, jobs.next_attempt_at
`

type ClaimJobParams struct {
	Role    string
	LeaseID string
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.Role, arg.LeaseID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Kind,
		&i.ResourceID,
		&i.State,
		&i.Payload,
		&i.Error,
		&i.Progress,
		&i.Attempts,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.CancelRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalFiles,
		&i.ProcessedFiles,
		&i.NextAttemptAt,
	)
	return i, err
}

const clearAccess = `-- name: ClearAccess :exec
DELETE FROM library_access WHERE user_id=$1
`

func (q *Queries) ClearAccess(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, clearAccess, userID)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(id,username,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id, username, password_hash, role, disabled, created_at
`

type CreateUserParams struct {
	ID           string
	Username     string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmptySeries = `-- name: DeleteEmptySeries :exec
DELETE FROM items i WHERE i.library_id=$1 AND i.kind='series'
AND NOT EXISTS (SELECT 1 FROM items child WHERE child.parent_id=i.id)
`

func (q *Queries) DeleteEmptySeries(ctx context.Context, libraryID string) error {
	_, err := q.db.Exec(ctx, deleteEmptySeries, libraryID)
	return err
}

const deleteLibrary = `-- name: DeleteLibrary :exec
DELETE FROM libraries WHERE id=$1
`

func (q *Queries) DeleteLibrary(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLibrary, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id=$1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const dueLibraries = `-- name: DueLibraries :many
SELECT id, name, kind, paths, scan_interval_hours, last_scan_at FROM libraries WHERE scan_interval_hours>0 AND last_scan_at+scan_interval_hours*interval '1 hour'<now()
`

func (q *Queries) DueLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.Query(ctx, dueLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Library{}
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Paths,
			&i.ScanIntervalHours,
			&i.LastScanAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueue = `-- name: Enqueue :one
INSERT INTO jobs(id,role,kind,resource_id,payload) VALUES($1,$2,$3,$4,$5) ON CONFLICT(kind,resource_id) WHERE state IN ('pending','running') DO UPDATE SET resource_id=excluded.resource_id RETURNING id, role, kind, resource_id, state, payload, error, progress, attempts, lease_id, lease_until, cancel_requested, created_at, updated_at, total_files, processed_files, next_attempt_at
`

type EnqueueParams struct {
	ID         string
	Role       string
	Kind       string
	ResourceID string
	Payload    []byte
}

func (q *Queries) Enqueue(ctx context.Context, arg EnqueueParams) (Job, error) {
	row := q.db.QueryRow(ctx, enqueue,
		arg.ID,
		arg.Role,
		arg.Kind,
		arg.ResourceID,
		arg.Payload,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Kind,
		&i.ResourceID,
		&i.State,
		&i.Payload,
		&i.Error,
		&i.Progress,
		&i.Attempts,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.CancelRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalFiles,
		&i.ProcessedFiles,
		&i.NextAttemptAt,
	)
	return i, err
}

const expirePlayback = `-- name: ExpirePlayback :exec
UPDATE playback_sessions SET state='stopped' WHERE state IN ('ready','preparing') AND (expires_at<now() OR updated_at<now()-interval '5 minutes')
`

func (q *Queries) ExpirePlayback(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expirePlayback)
	return err
}

const failPlayback = `-- name: FailPlayback :exec
UPDATE playback_sessions SET state='failed',updated_at=now() WHERE id=$1 AND state IN ('preparing','ready')
`

func (q *Queries) FailPlayback(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, failPlayback, id)
	return err
}

const fileByPath = `-- name: FileByPath :one
SELECT f.id, f.item_id, f.path, f.size, f.modified_at, f.duration, f.probe, f.available FROM media_files f JOIN items i ON i.id=f.item_id WHERE f.path=$1 AND i.library_id=$2
`

type FileByPathParams struct {
	Path      string
	LibraryID string
}

func (q *Queries) FileByPath(ctx context.Context, arg FileByPathParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, fileByPath, arg.Path, arg.LibraryID)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Path,
		&i.Size,
		&i.ModifiedAt,
		&i.Duration,
		&i.Probe,
		&i.Available,
	)
	return i, err
}

const finishJob = `-- name: FinishJob :exec
UPDATE jobs SET state=$3,error=$4,next_attempt_at=CASE WHEN $3='pending' THEN now()+least(300,10*attempts*attempts)*interval '1 second' ELSE next_attempt_at END,progress=CASE WHEN $3='completed' THEN 100 ELSE progress END,updated_at=now() WHERE id=$1 AND lease_id=$2 AND state='running'
`

type FinishJobParams struct {
	ID      string
	LeaseID string
	State   string
	Error   string
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.Exec(ctx, finishJob,
		arg.ID,
		arg.LeaseID,
		arg.State,
		arg.Error,
	)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, item_id, path, size, modified_at, duration, probe, available FROM media_files WHERE id=$1
`

func (q *Queries) GetFile(ctx context.Context, id string) (MediaFile, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Path,
		&i.Size,
		&i.ModifiedAt,
		&i.Duration,
		&i.Probe,
		&i.Available,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, library_id, parent_id, kind, title, sort_title, year, season, episode, overview, poster, provider_id, metadata_locked, created_at, cast_members FROM items WHERE id=$1
`

func (q *Queries) GetItem(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.SortTitle,
		&i.Year,
		&i.Season,
		&i.Episode,
		&i.Overview,
		&i.Poster,
		&i.ProviderID,
		&i.MetadataLocked,
		&i.CreatedAt,
		&i.CastMembers,
	)
	return i, err
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, name, kind, paths, scan_interval_hours, last_scan_at FROM libraries WHERE id=$1
`

func (q *Queries) GetLibrary(ctx context.Context, id string) (Library, error) {
	row := q.db.QueryRow(ctx, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Paths,
		&i.ScanIntervalHours,
		&i.LastScanAt,
	)
	return i, err
}

const getPlayback = `-- name: GetPlayback :one
SELECT id, user_id, item_id, file_id, token_hash, method, state, start_position, sequence, position, expires_at, updated_at FROM playback_sessions WHERE id=$1
`

func (q *Queries) GetPlayback(ctx context.Context, id string) (PlaybackSession, error) {
	row := q.db.QueryRow(ctx, getPlayback, id)
	var i PlaybackSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.FileID,
		&i.TokenHash,
		&i.Method,
		&i.State,
		&i.StartPosition,
		&i.Sequence,
		&i.Position,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key=$1
`

func (q *Queries) GetSetting(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const getState = `-- name: GetState :one
SELECT user_id, item_id, favorite, watched, position, updated_at FROM user_state WHERE user_id=$1 AND item_id=$2
`

type GetStateParams struct {
	UserID string
	ItemID string
}

func (q *Queries) GetState(ctx context.Context, arg GetStateParams) (UserState, error) {
	row := q.db.QueryRow(ctx, getState, arg.UserID, arg.ItemID)
	var i UserState
	err := row.Scan(
		&i.UserID,
		&i.ItemID,
		&i.Favorite,
		&i.Watched,
		&i.Position,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password_hash, role, disabled, created_at FROM users WHERE id=$1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const grantLibrary = `-- name: GrantLibrary :exec
INSERT INTO library_access(user_id,library_id) VALUES($1,$2) ON CONFLICT DO NOTHING
`

type GrantLibraryParams struct {
	UserID    string
	LibraryID string
}

func (q *Queries) GrantLibrary(ctx context.Context, arg GrantLibraryParams) error {
	_, err := q.db.Exec(ctx, grantLibrary, arg.UserID, arg.LibraryID)
	return err
}

const heartbeat = `-- name: Heartbeat :exec
INSERT INTO workers(id,role) VALUES($1,$2) ON CONFLICT(id) DO UPDATE SET heartbeat_at=now()
`

type HeartbeatParams struct {
	ID   string
	Role string
}

func (q *Queries) Heartbeat(ctx context.Context, arg HeartbeatParams) error {
	_, err := q.db.Exec(ctx, heartbeat, arg.ID, arg.Role)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,$3)
`

type InsertSessionParams struct {
	TokenHash string
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const itemFiles = `-- name: ItemFiles :many
SELECT id, item_id, path, size, modified_at, duration, probe, available FROM media_files WHERE item_id=$1 ORDER BY path
`

func (q *Queries) ItemFiles(ctx context.Context, itemID string) ([]MediaFile, error) {
	rows, err := q.db.Query(ctx, itemFiles, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaFile{}
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Path,
			&i.Size,
			&i.ModifiedAt,
			&i.Duration,
			&i.Probe,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestLibraryScan = `-- name: LatestLibraryScan :one
SELECT id, role, kind, resource_id, state, payload, error, progress, attempts, lease_id, lease_until, cancel_requested, created_at, updated_at, total_files, processed_files, next_attempt_at FROM jobs WHERE kind='scan' AND resource_id=$1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LatestLibraryScan(ctx context.Context, resourceID string) (Job, error) {
	row := q.db.QueryRow(ctx, latestLibraryScan, resourceID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Kind,
		&i.ResourceID,
		&i.State,
		&i.Payload,
		&i.Error,
		&i.Progress,
		&i.Attempts,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.CancelRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalFiles,
		&i.ProcessedFiles,
		&i.NextAttemptAt,
	)
	return i, err
}

const libraryFileCount = `-- name: LibraryFileCount :one
SELECT count(*) FROM media_files f JOIN items i ON i.id=f.item_id WHERE i.library_id=$1 AND f.available
`

func (q *Queries) LibraryFileCount(ctx context.Context, libraryID string) (int64, error) {
	row := q.db.QueryRow(ctx, libraryFileCount, libraryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const libraryFiles = `-- name: LibraryFiles :many
SELECT f.id, f.item_id, f.path, f.size, f.modified_at, f.duration, f.probe, f.available FROM media_files f JOIN items i ON i.id=f.item_id WHERE i.library_id=$1
`

func (q *Queries) LibraryFiles(ctx context.Context, libraryID string) ([]MediaFile, error) {
	rows, err := q.db.Query(ctx, libraryFiles, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaFile{}
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Path,
			&i.Size,
			&i.ModifiedAt,
			&i.Duration,
			&i.Probe,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT i.id, i.library_id, i.parent_id, i.kind, i.title, i.sort_title, i.year, i.season, i.episode, i.overview, i.poster, i.provider_id, i.metadata_locked, i.created_at, i.cast_members FROM items i WHERE
($1::boolean OR EXISTS(SELECT 1 FROM library_access a WHERE a.library_id=i.library_id AND a.user_id=$2::text))
AND ($3::text='' OR i.library_id=$3)
AND ($4::text='' OR i.parent_id=$4)
AND ($3::text='' OR $4::text<>'' OR $5::text<>'' OR i.parent_id='')
AND ($5::text='' OR i.kind=$5)
AND (NOT $6::boolean OR i.parent_id='' OR ($7::text<>'' AND i.kind IN ('track','podcast_episode','book_part')))
AND ($8::text='' OR EXISTS(SELECT 1 FROM audio_metadata a JOIN items child ON child.id=a.item_id WHERE (child.id=i.id OR child.parent_id=i.id) AND a.tags->'artists' ? $8))
AND ($9::text='' OR i.cast_members @> jsonb_build_array(jsonb_build_object('id',$9::text)))
AND ($7::text='' OR i.title ILIKE '%'||$7||'%' OR EXISTS(SELECT 1 FROM audio_metadata a WHERE a.item_id=i.id AND a.tags->>'artists' ILIKE '%'||$7||'%'))
AND (NOT $10::boolean OR EXISTS(SELECT 1 FROM user_state s WHERE s.user_id=$2 AND s.item_id=i.id AND s.favorite))
AND (NOT $11::boolean OR EXISTS(SELECT 1 FROM user_state s WHERE s.user_id=$2 AND s.item_id=i.id AND s.position>0 AND NOT s.watched))
AND (i.sort_title,i.id)>($12::text,$13::text)
ORDER BY i.sort_title,i.id LIMIT $14
`

type ListItemsParams struct {
	IsAdmin    bool
	UserID     string
	LibraryID  string
	ParentID   string
	Kind       string
	TopLevel   bool
	Search     string
	Artist     string
	PersonID   string
	Favorites  bool
	Resume     bool
	AfterTitle string
	AfterID    string
	PageLimit  int32
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.IsAdmin,
		arg.UserID,
		arg.LibraryID,
		arg.ParentID,
		arg.Kind,
		arg.TopLevel,
		arg.Search,
		arg.Artist,
		arg.PersonID,
		arg.Favorites,
		arg.Resume,
		arg.AfterTitle,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.ParentID,
			&i.Kind,
			&i.Title,
			&i.SortTitle,
			&i.Year,
			&i.Season,
			&i.Episode,
			&i.Overview,
			&i.Poster,
			&i.ProviderID,
			&i.MetadataLocked,
			&i.CreatedAt,
			&i.CastMembers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobDetails = `-- name: ListJobDetails :many
SELECT j.id, j.role, j.kind, j.resource_id, j.state, j.payload, j.error, j.progress, j.attempts, j.lease_id, j.lease_until, j.cancel_requested, j.created_at, j.updated_at, j.total_files, j.processed_files, j.next_attempt_at, COALESCE(l.name, i.title, pi.title, '')::text AS resource_name,
 COALESCE(i.id, pi.id, '')::text AS item_id,
 COALESCE(l.id, i.library_id, pi.library_id, '')::text AS library_id
FROM jobs j
LEFT JOIN libraries l ON j.kind='scan' AND l.id=j.resource_id
LEFT JOIN items i ON j.kind='metadata' AND i.id=j.resource_id
LEFT JOIN playback_sessions p ON j.kind='playback' AND p.id=j.resource_id
LEFT JOIN items pi ON pi.id=p.item_id
ORDER BY j.created_at DESC LIMIT 100
`

type ListJobDetailsRow struct {
	Job          Job
	ResourceName string
	ItemID       string
	LibraryID    string
}

func (q *Queries) ListJobDetails(ctx context.Context) ([]ListJobDetailsRow, error) {
	rows, err := q.db.Query(ctx, listJobDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobDetailsRow{}
	for rows.Next() {
		var i ListJobDetailsRow
		if err := rows.Scan(
			&i.Job.ID,
			&i.Job.Role,
			&i.Job.Kind,
			&i.Job.ResourceID,
			&i.Job.State,
			&i.Job.Payload,
			&i.Job.Error,
			&i.Job.Progress,
			&i.Job.Attempts,
			&i.Job.LeaseID,
			&i.Job.LeaseUntil,
			&i.Job.CancelRequested,
			&i.Job.CreatedAt,
			&i.Job.UpdatedAt,
			&i.Job.TotalFiles,
			&i.Job.ProcessedFiles,
			&i.Job.NextAttemptAt,
			&i.ResourceName,
			&i.ItemID,
			&i.LibraryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, role, kind, resource_id, state, payload, error, progress, attempts, lease_id, lease_until, cancel_requested, created_at, updated_at, total_files, processed_files, next_attempt_at FROM jobs ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Kind,
			&i.ResourceID,
			&i.State,
			&i.Payload,
			&i.Error,
			&i.Progress,
			&i.Attempts,
			&i.LeaseID,
			&i.LeaseUntil,
			&i.CancelRequested,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalFiles,
			&i.ProcessedFiles,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraries = `-- name: ListLibraries :many
SELECT l.id, l.name, l.kind, l.paths, l.scan_interval_hours, l.last_scan_at FROM libraries l WHERE $1::boolean OR EXISTS(SELECT 1 FROM library_access a WHERE a.library_id=l.id AND a.user_id=$2::text) ORDER BY name
`

type ListLibrariesParams struct {
	IsAdmin bool
	UserID  string
}

func (q *Queries) ListLibraries(ctx context.Context, arg ListLibrariesParams) ([]Library, error) {
	rows, err := q.db.Query(ctx, listLibraries, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Library{}
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Paths,
			&i.ScanIntervalHours,
			&i.LastScanAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, role, disabled, created_at FROM users ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Disabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkers = `-- name: ListWorkers :many
SELECT id, role, heartbeat_at, capabilities FROM workers WHERE heartbeat_at>now()-interval '60 seconds' ORDER BY role
`

func (q *Queries) ListWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.HeartbeatAt,
			&i.Capabilities,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSetup = `-- name: LockSetup :exec
SELECT pg_advisory_xact_lock(7311901)
`

func (q *Queries) LockSetup(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockSetup)
	return err
}

const lockTranscodes = `-- name: LockTranscodes :exec
SELECT pg_advisory_xact_lock(7311902)
`

func (q *Queries) LockTranscodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockTranscodes)
	return err
}

const patchSetting = `-- name: PatchSetting :exec
INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=settings.value || excluded.value
`

type PatchSettingParams struct {
	Key   string
	Value []byte
}

func (q *Queries) PatchSetting(ctx context.Context, arg PatchSettingParams) error {
	_, err := q.db.Exec(ctx, patchSetting, arg.Key, arg.Value)
	return err
}

const playbackProgress = `-- name: PlaybackProgress :one
UPDATE playback_sessions SET position=$3,sequence=$4,updated_at=now() WHERE id=$1 AND user_id=$2 AND sequence<$4 AND state IN ('ready','preparing') AND expires_at>now() RETURNING id, user_id, item_id, file_id, token_hash, method, state, start_position, sequence, position, expires_at, updated_at
`

type PlaybackProgressParams struct {
	ID       string
	UserID   string
	Position float64
	Sequence int64
}

func (q *Queries) PlaybackProgress(ctx context.Context, arg PlaybackProgressParams) (PlaybackSession, error) {
	row := q.db.QueryRow(ctx, playbackProgress,
		arg.ID,
		arg.UserID,
		arg.Position,
		arg.Sequence,
	)
	var i PlaybackSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.FileID,
		&i.TokenHash,
		&i.Method,
		&i.State,
		&i.StartPosition,
		&i.Sequence,
		&i.Position,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reapJobs = `-- name: ReapJobs :exec
UPDATE jobs SET state=CASE WHEN cancel_requested THEN 'cancelled' ELSE 'failed' END,error='Worker lease expired',updated_at=now() WHERE state='running' AND lease_until<now() AND (cancel_requested OR role='transcoder' OR attempts>=3)
`

func (q *Queries) ReapJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, reapJobs)
	return err
}

const reapPlayback = `-- name: ReapPlayback :exec
UPDATE playback_sessions SET state='failed' WHERE state IN ('preparing','ready') AND EXISTS(SELECT 1 FROM jobs j WHERE j.resource_id=playback_sessions.id AND j.role='transcoder' AND j.state IN ('failed','cancelled'))
`

func (q *Queries) ReapPlayback(ctx context.Context) error {
	_, err := q.db.Exec(ctx, reapPlayback)
	return err
}

const renewJob = `-- name: RenewJob :one
UPDATE jobs SET lease_until=now()+interval '30 seconds',updated_at=now() WHERE id=$1 AND lease_id=$2 AND state='running' AND NOT cancel_requested RETURNING id
`

type RenewJobParams struct {
	ID      string
	LeaseID string
}

func (q *Queries) RenewJob(ctx context.Context, arg RenewJobParams) (string, error) {
	row := q.db.QueryRow(ctx, renewJob, arg.ID, arg.LeaseID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const reportScan = `-- name: ReportScan :one
UPDATE jobs SET total_files=$3,processed_files=$4,progress=$5,updated_at=now()
WHERE id=$1 AND lease_id=$2 AND state='running' AND NOT cancel_requested AND lease_until>now() RETURNING id
`

type ReportScanParams struct {
	ID             string
	LeaseID        string
	TotalFiles     int32
	ProcessedFiles int32
	Progress       int32
}

func (q *Queries) ReportScan(ctx context.Context, arg ReportScanParams) (string, error) {
	row := q.db.QueryRow(ctx, reportScan,
		arg.ID,
		arg.LeaseID,
		arg.TotalFiles,
		arg.ProcessedFiles,
		arg.Progress,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const revokeSession = `-- name: RevokeSession :exec
DELETE FROM sessions WHERE token_hash=$1
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
DELETE FROM sessions WHERE user_id=$1
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const saveFile = `-- name: SaveFile :exec
INSERT INTO media_files(id,item_id,path,size,modified_at,duration,probe) VALUES($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT(item_id,path) DO UPDATE SET item_id=excluded.item_id,size=excluded.size,modified_at=excluded.modified_at,duration=excluded.duration,probe=excluded.probe,available=true
`

type SaveFileParams struct {
	ID         string
	ItemID     string
	Path       string
	Size       int64
	ModifiedAt int64
	Duration   float64
	Probe      []byte
}

func (q *Queries) SaveFile(ctx context.Context, arg SaveFileParams) error {
	_, err := q.db.Exec(ctx, saveFile,
		arg.ID,
		arg.ItemID,
		arg.Path,
		arg.Size,
		arg.ModifiedAt,
		arg.Duration,
		arg.Probe,
	)
	return err
}

const saveLibrary = `-- name: SaveLibrary :one
INSERT INTO libraries(id,name,kind,paths,scan_interval_hours) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO UPDATE SET name=excluded.name,paths=excluded.paths,scan_interval_hours=excluded.scan_interval_hours RETURNING id, name, kind, paths, scan_interval_hours, last_scan_at
`

type SaveLibraryParams struct {
	ID                string
	Name              string
	Kind              string
	Paths             []string
	ScanIntervalHours int32
}

func (q *Queries) SaveLibrary(ctx context.Context, arg SaveLibraryParams) (Library, error) {
	row := q.db.QueryRow(ctx, saveLibrary,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Paths,
		arg.ScanIntervalHours,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Paths,
		&i.ScanIntervalHours,
		&i.LastScanAt,
	)
	return i, err
}

const saveMetadata = `-- name: SaveMetadata :one
UPDATE items SET title=$2,sort_title=lower($2),year=$3,overview=$4,poster=$5,provider_id=$6,metadata_locked=$7,cast_members=$8 WHERE id=$1 RETURNING id, library_id, parent_id, kind, title, sort_title, year, season, episode, overview, poster, provider_id, metadata_locked, created_at, cast_members
`

type SaveMetadataParams struct {
	ID             string
	Title          string
	Year           int32
	Overview       string
	Poster         string
	ProviderID     string
	MetadataLocked bool
	CastMembers    []byte
}

func (q *Queries) SaveMetadata(ctx context.Context, arg SaveMetadataParams) (Item, error) {
	row := q.db.QueryRow(ctx, saveMetadata,
		arg.ID,
		arg.Title,
		arg.Year,
		arg.Overview,
		arg.Poster,
		arg.ProviderID,
		arg.MetadataLocked,
		arg.CastMembers,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.SortTitle,
		&i.Year,
		&i.Season,
		&i.Episode,
		&i.Overview,
		&i.Poster,
		&i.ProviderID,
		&i.MetadataLocked,
		&i.CreatedAt,
		&i.CastMembers,
	)
	return i, err
}

const saveProgress = `-- name: SaveProgress :exec
INSERT INTO user_state(user_id,item_id,position,watched) VALUES($1,$2,$3,$4) ON CONFLICT(user_id,item_id) DO UPDATE SET position=excluded.position,watched=excluded.watched,updated_at=now()
`

type SaveProgressParams struct {
	UserID   string
	ItemID   string
	Position float64
	Watched  bool
}

func (q *Queries) SaveProgress(ctx context.Context, arg SaveProgressParams) error {
	_, err := q.db.Exec(ctx, saveProgress,
		arg.UserID,
		arg.ItemID,
		arg.Position,
		arg.Watched,
	)
	return err
}

const saveSetting = `-- name: SaveSetting :exec
INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=excluded.value
`

type SaveSettingParams struct {
	Key   string
	Value []byte
}

func (q *Queries) SaveSetting(ctx context.Context, arg SaveSettingParams) error {
	_, err := q.db.Exec(ctx, saveSetting, arg.Key, arg.Value)
	return err
}

const scannedLibrary = `-- name: ScannedLibrary :exec
UPDATE libraries SET last_scan_at=now() WHERE id=$1
`

func (q *Queries) ScannedLibrary(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, scannedLibrary, id)
	return err
}

const setPlaybackReady = `-- name: SetPlaybackReady :exec
UPDATE playback_sessions SET state='ready',updated_at=now() WHERE id=$1 AND state='preparing'
`

func (q *Queries) SetPlaybackReady(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setPlaybackReady, id)
	return err
}

const setState = `-- name: SetState :one
INSERT INTO user_state(user_id,item_id,favorite,watched) VALUES($1,$2,$3,$4) ON CONFLICT(user_id,item_id) DO UPDATE SET favorite=excluded.favorite,watched=excluded.watched,updated_at=now() RETURNING user_id, item_id, favorite, watched, position, updated_at
`

type SetStateParams struct {
	UserID   string
	ItemID   string
	Favorite bool
	Watched  bool
}

func (q *Queries) SetState(ctx context.Context, arg SetStateParams) (UserState, error) {
	row := q.db.QueryRow(ctx, setState,
		arg.UserID,
		arg.ItemID,
		arg.Favorite,
		arg.Watched,
	)
	var i UserState
	err := row.Scan(
		&i.UserID,
		&i.ItemID,
		&i.Favorite,
		&i.Watched,
		&i.Position,
		&i.UpdatedAt,
	)
	return i, err
}

const startPlayback = `-- name: StartPlayback :exec
INSERT INTO playback_sessions(id,user_id,item_id,file_id,token_hash,method,state,start_position,position,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8,$9)
`

type StartPlaybackParams struct {
	ID            string
	UserID        string
	ItemID        string
	FileID        string
	TokenHash     string
	Method        string
	State         string
	StartPosition float64
	ExpiresAt     time.Time
}

func (q *Queries) StartPlayback(ctx context.Context, arg StartPlaybackParams) error {
	_, err := q.db.Exec(ctx, startPlayback,
		arg.ID,
		arg.UserID,
		arg.ItemID,
		arg.FileID,
		arg.TokenHash,
		arg.Method,
		arg.State,
		arg.StartPosition,
		arg.ExpiresAt,
	)
	return err
}

const stopPlayback = `-- name: StopPlayback :exec
UPDATE playback_sessions SET state='stopped',updated_at=now() WHERE id=$1 AND user_id=$2
`

type StopPlaybackParams struct {
	ID     string
	UserID string
}

func (q *Queries) StopPlayback(ctx context.Context, arg StopPlaybackParams) error {
	_, err := q.db.Exec(ctx, stopPlayback, arg.ID, arg.UserID)
	return err
}

const unavailableFile = `-- name: UnavailableFile :exec
UPDATE media_files SET available=false WHERE id=$1
`

func (q *Queries) UnavailableFile(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, unavailableFile, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash=$2 WHERE id=$1
`

type UpdatePasswordParams struct {
	ID           string
	PasswordHash string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET username=$2,role=$3,disabled=$4 WHERE id=$1 RETURNING id, username, password_hash, role, disabled, created_at
`

type UpdateUserParams struct {
	ID       string
	Username string
	Role     string
	Disabled bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Role,
		arg.Disabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const upsertItem = `-- name: UpsertItem :exec
INSERT INTO items(id,library_id,parent_id,kind,title,sort_title,year,season,episode) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT(id) DO UPDATE SET parent_id=excluded.parent_id,season=excluded.season,episode=excluded.episode
`

type UpsertItemParams struct {
	ID        string
	LibraryID string
	ParentID  string
	Kind      string
	Title     string
	SortTitle string
	Year      int32
	Season    int32
	Episode   int32
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) error {
	_, err := q.db.Exec(ctx, upsertItem,
		arg.ID,
		arg.LibraryID,
		arg.ParentID,
		arg.Kind,
		arg.Title,
		arg.SortTitle,
		arg.Year,
		arg.Season,
		arg.Episode,
	)
	return err
}

const userByName = `-- name: UserByName :one
SELECT id, username, password_hash, role, disabled, created_at FROM users WHERE username=$1
`

func (q *Queries) UserByName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, userByName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const userLibraries = `-- name: UserLibraries :many
SELECT library_id FROM library_access WHERE user_id=$1
`

func (q *Queries) UserLibraries(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, userLibraries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var library_id string
		if err := rows.Scan(&library_id); err != nil {
			return nil, err
		}
		items = append(items, library_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
