// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subtitles.sql

package store

import (
	"context"
)

const getSubtitle = `-- name: GetSubtitle :one
SELECT id, file_id, user_id, name, cues, created_at FROM uploaded_subtitles WHERE id=$1 AND file_id=$2 AND user_id=$3
`

type GetSubtitleParams struct {
	ID     string
	FileID string
	UserID string
}

func (q *Queries) GetSubtitle(ctx context.Context, arg GetSubtitleParams) (UploadedSubtitle, error) {
	row := q.db.QueryRow(ctx, getSubtitle, arg.ID, arg.FileID, arg.UserID)
	var i UploadedSubtitle
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.UserID,
		&i.Name,
		&i.Cues,
		&i.CreatedAt,
	)
	return i, err
}

const listSubtitles = `-- name: ListSubtitles :many
SELECT id,name,jsonb_array_length(cues)::int AS cue_count FROM uploaded_subtitles WHERE file_id=$1 AND user_id=$2 ORDER BY created_at,id
`

type ListSubtitlesParams struct {
	FileID string
	UserID string
}

type ListSubtitlesRow struct {
	ID       string
	Name     string
	CueCount int32
}

func (q *Queries) ListSubtitles(ctx context.Context, arg ListSubtitlesParams) ([]ListSubtitlesRow, error) {
	rows, err := q.db.Query(ctx, listSubtitles, arg.FileID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubtitlesRow{}
	for rows.Next() {
		var i ListSubtitlesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CueCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSubtitle = `-- name: SaveSubtitle :one
INSERT INTO uploaded_subtitles(id,file_id,user_id,name,cues) VALUES($1,$2,$3,$4,$5) RETURNING id,name,jsonb_array_length(cues)::int AS cue_count
`

type SaveSubtitleParams struct {
	ID     string
	FileID string
	UserID string
	Name   string
	Cues   []byte
}

type SaveSubtitleRow struct {
	ID       string
	Name     string
	CueCount int32
}

func (q *Queries) SaveSubtitle(ctx context.Context, arg SaveSubtitleParams) (SaveSubtitleRow, error) {
	row := q.db.QueryRow(ctx, saveSubtitle,
		arg.ID,
		arg.FileID,
		arg.UserID,
		arg.Name,
		arg.Cues,
	)
	var i SaveSubtitleRow
	err := row.Scan(&i.ID, &i.Name, &i.CueCount)
	return i, err
}
