// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subtitle_timing.sql

package store

import (
	"context"
)

const clearOriginalSubtitleTiming = `-- name: ClearOriginalSubtitleTiming :exec
DELETE FROM personal_subtitle_timing WHERE file_id=$1 AND source_key LIKE 'track:%'
`

func (q *Queries) ClearOriginalSubtitleTiming(ctx context.Context, fileID string) error {
	_, err := q.db.Exec(ctx, clearOriginalSubtitleTiming, fileID)
	return err
}

const deletePersonalSubtitleTiming = `-- name: DeletePersonalSubtitleTiming :exec
DELETE FROM personal_subtitle_timing WHERE user_id=$1 AND file_id=$2 AND source_key=$3
`

type DeletePersonalSubtitleTimingParams struct {
	UserID    string
	FileID    string
	SourceKey string
}

func (q *Queries) DeletePersonalSubtitleTiming(ctx context.Context, arg DeletePersonalSubtitleTimingParams) error {
	_, err := q.db.Exec(ctx, deletePersonalSubtitleTiming, arg.UserID, arg.FileID, arg.SourceKey)
	return err
}

const listPersonalSubtitleTiming = `-- name: ListPersonalSubtitleTiming :many
SELECT source_key,offset_ms FROM personal_subtitle_timing WHERE user_id=$1 AND file_id=$2
`

type ListPersonalSubtitleTimingParams struct {
	UserID string
	FileID string
}

type ListPersonalSubtitleTimingRow struct {
	SourceKey string
	OffsetMs  int32
}

func (q *Queries) ListPersonalSubtitleTiming(ctx context.Context, arg ListPersonalSubtitleTimingParams) ([]ListPersonalSubtitleTimingRow, error) {
	rows, err := q.db.Query(ctx, listPersonalSubtitleTiming, arg.UserID, arg.FileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalSubtitleTimingRow{}
	for rows.Next() {
		var i ListPersonalSubtitleTimingRow
		if err := rows.Scan(&i.SourceKey, &i.OffsetMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePersonalSubtitleTiming = `-- name: SavePersonalSubtitleTiming :exec
INSERT INTO personal_subtitle_timing(user_id,file_id,source_key,offset_ms) VALUES($1,$2,$3,$4)
ON CONFLICT(user_id,file_id,source_key) DO UPDATE SET offset_ms=EXCLUDED.offset_ms
`

type SavePersonalSubtitleTimingParams struct {
	UserID    string
	FileID    string
	SourceKey string
	OffsetMs  int32
}

func (q *Queries) SavePersonalSubtitleTiming(ctx context.Context, arg SavePersonalSubtitleTimingParams) error {
	_, err := q.db.Exec(ctx, savePersonalSubtitleTiming,
		arg.UserID,
		arg.FileID,
		arg.SourceKey,
		arg.OffsetMs,
	)
	return err
}
