// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subtitle_sync.sql

package store

import (
	"context"
)

const canEditSubtitles = `-- name: CanEditSubtitles :one
SELECT EXISTS(SELECT 1 FROM users u JOIN libraries l ON l.id=$1
WHERE u.id=$2 AND NOT u.disabled AND l.kind IN ('movies','series')
AND (u.role='admin' OR EXISTS(SELECT 1 FROM library_access a WHERE a.user_id=u.id AND a.library_id=l.id AND a.can_import)))::boolean
`

type CanEditSubtitlesParams struct {
	LibraryID string
	UserID    string
}

func (q *Queries) CanEditSubtitles(ctx context.Context, arg CanEditSubtitlesParams) (bool, error) {
	row := q.db.QueryRow(ctx, canEditSubtitles, arg.LibraryID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const completeRecoveredSubtitleJob = `-- name: CompleteRecoveredSubtitleJob :exec
UPDATE jobs SET state='completed',error='',progress=100,updated_at=now() WHERE id=$1 AND state IN ('failed','cancelled')
`

func (q *Queries) CompleteRecoveredSubtitleJob(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, completeRecoveredSubtitleJob, id)
	return err
}

const createSubtitleSyncJob = `-- name: CreateSubtitleSyncJob :exec
INSERT INTO subtitle_sync_jobs(id,user_id,file_id,track_index,action,fingerprint,offset_ms,probe_revision) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type CreateSubtitleSyncJobParams struct {
	ID            string
	UserID        string
	FileID        string
	TrackIndex    int32
	Action        string
	Fingerprint   string
	OffsetMs      int32
	ProbeRevision string
}

func (q *Queries) CreateSubtitleSyncJob(ctx context.Context, arg CreateSubtitleSyncJobParams) error {
	_, err := q.db.Exec(ctx, createSubtitleSyncJob,
		arg.ID,
		arg.UserID,
		arg.FileID,
		arg.TrackIndex,
		arg.Action,
		arg.Fingerprint,
		arg.OffsetMs,
		arg.ProbeRevision,
	)
	return err
}

const deleteUploadedSubtitle = `-- name: DeleteUploadedSubtitle :one
DELETE FROM uploaded_subtitles WHERE id=$1 AND file_id=$2 AND user_id=$3 RETURNING id
`

type DeleteUploadedSubtitleParams struct {
	ID     string
	FileID string
	UserID string
}

func (q *Queries) DeleteUploadedSubtitle(ctx context.Context, arg DeleteUploadedSubtitleParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteUploadedSubtitle, arg.ID, arg.FileID, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getSubtitleSyncJob = `-- name: GetSubtitleSyncJob :one
SELECT id, user_id, file_id, track_index, probe_revision, action, fingerprint, offset_ms, source_path, cues, phase, error_code FROM subtitle_sync_jobs WHERE id=$1
`

func (q *Queries) GetSubtitleSyncJob(ctx context.Context, id string) (SubtitleSyncJob, error) {
	row := q.db.QueryRow(ctx, getSubtitleSyncJob, id)
	var i SubtitleSyncJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileID,
		&i.TrackIndex,
		&i.ProbeRevision,
		&i.Action,
		&i.Fingerprint,
		&i.OffsetMs,
		&i.SourcePath,
		&i.Cues,
		&i.Phase,
		&i.ErrorCode,
	)
	return i, err
}

const librarySubtitleBusy = `-- name: LibrarySubtitleBusy :one
SELECT EXISTS(SELECT 1 FROM subtitle_sync_jobs s JOIN media_files f ON f.id=s.file_id JOIN items i ON i.id=f.item_id
WHERE i.library_id=$1 AND s.action<>'prepare' AND s.phase NOT IN ('indexed','abandoned'))::boolean
`

func (q *Queries) LibrarySubtitleBusy(ctx context.Context, libraryID string) (bool, error) {
	row := q.db.QueryRow(ctx, librarySubtitleBusy, libraryID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const lockSubtitleFile = `-- name: LockSubtitleFile :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 7311904))
`

func (q *Queries) LockSubtitleFile(ctx context.Context, fileID string) error {
	_, err := q.db.Exec(ctx, lockSubtitleFile, fileID)
	return err
}

const lockSubtitleLibrary = `-- name: LockSubtitleLibrary :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 7311905))
`

func (q *Queries) LockSubtitleLibrary(ctx context.Context, libraryID string) error {
	_, err := q.db.Exec(ctx, lockSubtitleLibrary, libraryID)
	return err
}

const prepareSubtitleSyncJob = `-- name: PrepareSubtitleSyncJob :exec
UPDATE subtitle_sync_jobs SET fingerprint=$2,source_path=$3,cues=$4,phase='ready' WHERE id=$1
`

type PrepareSubtitleSyncJobParams struct {
	ID          string
	Fingerprint string
	SourcePath  string
	Cues        []byte
}

func (q *Queries) PrepareSubtitleSyncJob(ctx context.Context, arg PrepareSubtitleSyncJobParams) error {
	_, err := q.db.Exec(ctx, prepareSubtitleSyncJob,
		arg.ID,
		arg.Fingerprint,
		arg.SourcePath,
		arg.Cues,
	)
	return err
}

const recoverableSubtitleJobs = `-- name: RecoverableSubtitleJobs :many
SELECT s.id, s.user_id, s.file_id, s.track_index, s.probe_revision, s.action, s.fingerprint, s.offset_ms, s.source_path, s.cues, s.phase, s.error_code FROM subtitle_sync_jobs s JOIN jobs j ON j.id=s.id WHERE s.action<>'prepare' AND s.phase<>'abandoned' AND j.state IN ('failed','cancelled') LIMIT 100
`

func (q *Queries) RecoverableSubtitleJobs(ctx context.Context) ([]SubtitleSyncJob, error) {
	rows, err := q.db.Query(ctx, recoverableSubtitleJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubtitleSyncJob{}
	for rows.Next() {
		var i SubtitleSyncJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileID,
			&i.TrackIndex,
			&i.ProbeRevision,
			&i.Action,
			&i.Fingerprint,
			&i.OffsetMs,
			&i.SourcePath,
			&i.Cues,
			&i.Phase,
			&i.ErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSubtitleSyncPhase = `-- name: SetSubtitleSyncPhase :exec
UPDATE subtitle_sync_jobs SET phase=$2,error_code=$3 WHERE id=$1
`

type SetSubtitleSyncPhaseParams struct {
	ID        string
	Phase     string
	ErrorCode string
}

func (q *Queries) SetSubtitleSyncPhase(ctx context.Context, arg SetSubtitleSyncPhaseParams) error {
	_, err := q.db.Exec(ctx, setSubtitleSyncPhase, arg.ID, arg.Phase, arg.ErrorCode)
	return err
}

const subtitleFileBusy = `-- name: SubtitleFileBusy :one
SELECT EXISTS(SELECT 1 FROM subtitle_sync_jobs s JOIN jobs j ON j.id=s.id WHERE s.file_id=$1 AND s.action<>'prepare' AND (j.state IN ('pending','running') OR s.phase IN ('prepared','published')))::boolean
`

func (q *Queries) SubtitleFileBusy(ctx context.Context, fileID string) (bool, error) {
	row := q.db.QueryRow(ctx, subtitleFileBusy, fileID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const subtitleMKVWorkerReady = `-- name: SubtitleMKVWorkerReady :one
SELECT EXISTS(SELECT 1 FROM workers WHERE role='scanner' AND heartbeat_at>now()-interval '60 seconds' AND capabilities->>'subtitleMKV'='true')::boolean
`

func (q *Queries) SubtitleMKVWorkerReady(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, subtitleMKVWorkerReady)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const subtitlePlaybackBusy = `-- name: SubtitlePlaybackBusy :one
SELECT EXISTS(SELECT 1 FROM playback_sessions WHERE file_id=$1 AND state IN ('ready','preparing') AND expires_at>now() AND updated_at>now()-interval '5 minutes')::boolean
`

func (q *Queries) SubtitlePlaybackBusy(ctx context.Context, fileID string) (bool, error) {
	row := q.db.QueryRow(ctx, subtitlePlaybackBusy, fileID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const subtitleSyncWorkerReady = `-- name: SubtitleSyncWorkerReady :one
SELECT EXISTS(SELECT 1 FROM workers WHERE role='scanner' AND heartbeat_at>now()-interval '60 seconds' AND capabilities->>'subtitleSync'='true')::boolean
`

func (q *Queries) SubtitleSyncWorkerReady(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, subtitleSyncWorkerReady)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const subtitleTranscoderBusy = `-- name: SubtitleTranscoderBusy :one
SELECT EXISTS(SELECT 1 FROM jobs j JOIN playback_sessions p ON p.id=j.resource_id WHERE p.file_id=$1 AND j.kind='playback' AND j.state='running')::boolean
`

func (q *Queries) SubtitleTranscoderBusy(ctx context.Context, fileID string) (bool, error) {
	row := q.db.QueryRow(ctx, subtitleTranscoderBusy, fileID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateSubtitleFileProbe = `-- name: UpdateSubtitleFileProbe :exec
UPDATE media_files SET probe=$2,size=$3,modified_at=$4 WHERE id=$1
`

type UpdateSubtitleFileProbeParams struct {
	ID         string
	Probe      []byte
	Size       int64
	ModifiedAt int64
}

func (q *Queries) UpdateSubtitleFileProbe(ctx context.Context, arg UpdateSubtitleFileProbeParams) error {
	_, err := q.db.Exec(ctx, updateSubtitleFileProbe,
		arg.ID,
		arg.Probe,
		arg.Size,
		arg.ModifiedAt,
	)
	return err
}
